name: 'Running AQA test'
description: 'Running AQA test'
author: 'Sophia Guo'
inputs:
  version:              # jdk version
    description: 'testing jdk version'
    default: '8'
  architecture:         # architecture
    description: 
    default: 'x86'
  build_list:           # test catagory
    description: 
    default: 'openjdk'
  target:              # test
    description: 
    default: '_jdk_custom'
runs:
  using: 'node12'
  main: 'dist/index.js'
